# Generated by Django 3.1 on 2020-10-02 10:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=models.ImageField(default=datetime.datetime(2020, 10, 2, 10, 56, 44, 561102, tzinfo=utc), upload_to='images'),
            preserve_default=False,
        ),
    ]
